/* soapH.h
   Generated by gSOAP 2.8.1 from EpcTagDataTranslation.h
   Copyright(C) 2000-2010, Robert van Engelen, Genivia Inc. All Rights Reserved.
   The generated code is released under one of the following licenses:
   GPL OR Genivia's license for commercial use.
*/

#ifndef soapH_H
#define soapH_H
#include "soapStub.h"
#ifdef __cplusplus
extern "C" {
#endif
#ifndef WITH_NOIDREF
SOAP_FMAC3 void SOAP_FMAC4 soap_markelement(struct soap*, const void*, int);
SOAP_FMAC3 int SOAP_FMAC4 soap_putelement(struct soap*, const void*, const char*, int, int);
SOAP_FMAC3 void *SOAP_FMAC4 soap_getelement(struct soap*, int*);
SOAP_FMAC3 int SOAP_FMAC4 soap_putindependent(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_getindependent(struct soap*);
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_ignore_element(struct soap*);

#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (3)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_byte(struct soap*, char *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_byte(struct soap*, const char*, int, const char *, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_in_byte(struct soap*, const char*, char *, const char*);

#ifndef soap_write_byte
#define soap_write_byte(soap, data) ( soap_begin_send(soap) || soap_put_byte(soap, data, "byte", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_byte(struct soap*, const char *, const char*, const char*);

#ifndef soap_read_byte
#define soap_read_byte(soap, data) ( soap_begin_recv(soap) || !soap_get_byte(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 char * SOAP_FMAC4 soap_get_byte(struct soap*, char *, const char*, const char*);

#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_int(struct soap*, int *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_int(struct soap*, const char*, int *, const char*);

#ifndef soap_write_int
#define soap_write_int(soap, data) ( soap_begin_send(soap) || soap_put_int(soap, data, "int", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_int(struct soap*, const int *, const char*, const char*);

#ifndef soap_read_int
#define soap_read_int(soap, data) ( soap_begin_recv(soap) || !soap_get_int(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 int * SOAP_FMAC4 soap_get_int(struct soap*, int *, const char*, const char*);

#ifndef SOAP_TYPE_time
#define SOAP_TYPE_time (26)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_time(struct soap*, time_t *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_time(struct soap*, const char*, int, const time_t *, const char*);
SOAP_FMAC3 time_t * SOAP_FMAC4 soap_in_time(struct soap*, const char*, time_t *, const char*);

#ifndef soap_write_time
#define soap_write_time(soap, data) ( soap_begin_send(soap) || soap_put_time(soap, data, "dateTime", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_time(struct soap*, const time_t *, const char*, const char*);

#ifndef soap_read_time
#define soap_read_time(soap, data) ( soap_begin_recv(soap) || !soap_get_time(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 time_t * SOAP_FMAC4 soap_get_time(struct soap*, time_t *, const char*, const char*);

#ifndef SOAP_TYPE_tdt__PadDirectionList
#define SOAP_TYPE_tdt__PadDirectionList (12)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_tdt__PadDirectionList(struct soap*, enum tdt__PadDirectionList *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_tdt__PadDirectionList(struct soap*, const char*, int, const enum tdt__PadDirectionList *, const char*);

SOAP_FMAC3S const char* SOAP_FMAC4S soap_tdt__PadDirectionList2s(struct soap*, enum tdt__PadDirectionList);
SOAP_FMAC3 enum tdt__PadDirectionList * SOAP_FMAC4 soap_in_tdt__PadDirectionList(struct soap*, const char*, enum tdt__PadDirectionList *, const char*);

SOAP_FMAC3S int SOAP_FMAC4S soap_s2tdt__PadDirectionList(struct soap*, const char*, enum tdt__PadDirectionList *);

#ifndef soap_write_tdt__PadDirectionList
#define soap_write_tdt__PadDirectionList(soap, data) ( soap_begin_send(soap) || soap_put_tdt__PadDirectionList(soap, data, "tdt:PadDirectionList", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_tdt__PadDirectionList(struct soap*, const enum tdt__PadDirectionList *, const char*, const char*);

#ifndef soap_read_tdt__PadDirectionList
#define soap_read_tdt__PadDirectionList(soap, data) ( soap_begin_recv(soap) || !soap_get_tdt__PadDirectionList(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 enum tdt__PadDirectionList * SOAP_FMAC4 soap_get_tdt__PadDirectionList(struct soap*, enum tdt__PadDirectionList *, const char*, const char*);

#ifndef SOAP_TYPE_tdt__CompactionMethodList
#define SOAP_TYPE_tdt__CompactionMethodList (11)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_tdt__CompactionMethodList(struct soap*, enum tdt__CompactionMethodList *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_tdt__CompactionMethodList(struct soap*, const char*, int, const enum tdt__CompactionMethodList *, const char*);

SOAP_FMAC3S const char* SOAP_FMAC4S soap_tdt__CompactionMethodList2s(struct soap*, enum tdt__CompactionMethodList);
SOAP_FMAC3 enum tdt__CompactionMethodList * SOAP_FMAC4 soap_in_tdt__CompactionMethodList(struct soap*, const char*, enum tdt__CompactionMethodList *, const char*);

SOAP_FMAC3S int SOAP_FMAC4S soap_s2tdt__CompactionMethodList(struct soap*, const char*, enum tdt__CompactionMethodList *);

#ifndef soap_write_tdt__CompactionMethodList
#define soap_write_tdt__CompactionMethodList(soap, data) ( soap_begin_send(soap) || soap_put_tdt__CompactionMethodList(soap, data, "tdt:CompactionMethodList", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_tdt__CompactionMethodList(struct soap*, const enum tdt__CompactionMethodList *, const char*, const char*);

#ifndef soap_read_tdt__CompactionMethodList
#define soap_read_tdt__CompactionMethodList(soap, data) ( soap_begin_recv(soap) || !soap_get_tdt__CompactionMethodList(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 enum tdt__CompactionMethodList * SOAP_FMAC4 soap_get_tdt__CompactionMethodList(struct soap*, enum tdt__CompactionMethodList *, const char*, const char*);

#ifndef SOAP_TYPE_tdt__ModeList
#define SOAP_TYPE_tdt__ModeList (10)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_tdt__ModeList(struct soap*, enum tdt__ModeList *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_tdt__ModeList(struct soap*, const char*, int, const enum tdt__ModeList *, const char*);

SOAP_FMAC3S const char* SOAP_FMAC4S soap_tdt__ModeList2s(struct soap*, enum tdt__ModeList);
SOAP_FMAC3 enum tdt__ModeList * SOAP_FMAC4 soap_in_tdt__ModeList(struct soap*, const char*, enum tdt__ModeList *, const char*);

SOAP_FMAC3S int SOAP_FMAC4S soap_s2tdt__ModeList(struct soap*, const char*, enum tdt__ModeList *);

#ifndef soap_write_tdt__ModeList
#define soap_write_tdt__ModeList(soap, data) ( soap_begin_send(soap) || soap_put_tdt__ModeList(soap, data, "tdt:ModeList", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_tdt__ModeList(struct soap*, const enum tdt__ModeList *, const char*, const char*);

#ifndef soap_read_tdt__ModeList
#define soap_read_tdt__ModeList(soap, data) ( soap_begin_recv(soap) || !soap_get_tdt__ModeList(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 enum tdt__ModeList * SOAP_FMAC4 soap_get_tdt__ModeList(struct soap*, enum tdt__ModeList *, const char*, const char*);

#ifndef SOAP_TYPE_tdt__InputFormatList
#define SOAP_TYPE_tdt__InputFormatList (9)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_tdt__InputFormatList(struct soap*, enum tdt__InputFormatList *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_tdt__InputFormatList(struct soap*, const char*, int, const enum tdt__InputFormatList *, const char*);

SOAP_FMAC3S const char* SOAP_FMAC4S soap_tdt__InputFormatList2s(struct soap*, enum tdt__InputFormatList);
SOAP_FMAC3 enum tdt__InputFormatList * SOAP_FMAC4 soap_in_tdt__InputFormatList(struct soap*, const char*, enum tdt__InputFormatList *, const char*);

SOAP_FMAC3S int SOAP_FMAC4S soap_s2tdt__InputFormatList(struct soap*, const char*, enum tdt__InputFormatList *);

#ifndef soap_write_tdt__InputFormatList
#define soap_write_tdt__InputFormatList(soap, data) ( soap_begin_send(soap) || soap_put_tdt__InputFormatList(soap, data, "tdt:InputFormatList", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_tdt__InputFormatList(struct soap*, const enum tdt__InputFormatList *, const char*, const char*);

#ifndef soap_read_tdt__InputFormatList
#define soap_read_tdt__InputFormatList(soap, data) ( soap_begin_recv(soap) || !soap_get_tdt__InputFormatList(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 enum tdt__InputFormatList * SOAP_FMAC4 soap_get_tdt__InputFormatList(struct soap*, enum tdt__InputFormatList *, const char*, const char*);

#ifndef SOAP_TYPE_tdt__LevelTypeList
#define SOAP_TYPE_tdt__LevelTypeList (8)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_tdt__LevelTypeList(struct soap*, enum tdt__LevelTypeList *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_tdt__LevelTypeList(struct soap*, const char*, int, const enum tdt__LevelTypeList *, const char*);

SOAP_FMAC3S const char* SOAP_FMAC4S soap_tdt__LevelTypeList2s(struct soap*, enum tdt__LevelTypeList);
SOAP_FMAC3 enum tdt__LevelTypeList * SOAP_FMAC4 soap_in_tdt__LevelTypeList(struct soap*, const char*, enum tdt__LevelTypeList *, const char*);

SOAP_FMAC3S int SOAP_FMAC4S soap_s2tdt__LevelTypeList(struct soap*, const char*, enum tdt__LevelTypeList *);

#ifndef soap_write_tdt__LevelTypeList
#define soap_write_tdt__LevelTypeList(soap, data) ( soap_begin_send(soap) || soap_put_tdt__LevelTypeList(soap, data, "tdt:LevelTypeList", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_tdt__LevelTypeList(struct soap*, const enum tdt__LevelTypeList *, const char*, const char*);

#ifndef soap_read_tdt__LevelTypeList
#define soap_read_tdt__LevelTypeList(soap, data) ( soap_begin_recv(soap) || !soap_get_tdt__LevelTypeList(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 enum tdt__LevelTypeList * SOAP_FMAC4 soap_get_tdt__LevelTypeList(struct soap*, enum tdt__LevelTypeList *, const char*, const char*);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (34)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Fault(struct soap*, const char*, int, const struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_in_SOAP_ENV__Fault(struct soap*, const char*, struct SOAP_ENV__Fault *, const char*);

#ifndef soap_write_SOAP_ENV__Fault
#define soap_write_SOAP_ENV__Fault(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Fault(soap, data), 0) || soap_put_SOAP_ENV__Fault(soap, data, "SOAP-ENV:Fault", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Fault
#define soap_read_SOAP_ENV__Fault(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Fault(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_get_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *, const char*, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (33)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Reason(struct soap*, const char*, int, const struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_in_SOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason *, const char*);

#ifndef soap_write_SOAP_ENV__Reason
#define soap_write_SOAP_ENV__Reason(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Reason(soap, data), 0) || soap_put_SOAP_ENV__Reason(soap, data, "SOAP-ENV:Reason", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Reason
#define soap_read_SOAP_ENV__Reason(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_get_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *, const char*, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (30)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Detail(struct soap*, const char*, int, const struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_in_SOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail *, const char*);

#ifndef soap_write_SOAP_ENV__Detail
#define soap_write_SOAP_ENV__Detail(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Detail(soap, data), 0) || soap_put_SOAP_ENV__Detail(soap, data, "SOAP-ENV:Detail", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Detail
#define soap_read_SOAP_ENV__Detail(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_get_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *, const char*, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (28)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Code(struct soap*, const char*, int, const struct SOAP_ENV__Code *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_in_SOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code *, const char*);

#ifndef soap_write_SOAP_ENV__Code
#define soap_write_SOAP_ENV__Code(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Code(soap, data), 0) || soap_put_SOAP_ENV__Code(soap, data, "SOAP-ENV:Code", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Code
#define soap_read_SOAP_ENV__Code(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_get_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *, const char*, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (27)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Header(struct soap*, const char*, int, const struct SOAP_ENV__Header *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_in_SOAP_ENV__Header(struct soap*, const char*, struct SOAP_ENV__Header *, const char*);

#ifndef soap_write_SOAP_ENV__Header
#define soap_write_SOAP_ENV__Header(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Header(soap, data), 0) || soap_put_SOAP_ENV__Header(soap, data, "SOAP-ENV:Header", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Header
#define soap_read_SOAP_ENV__Header(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Header(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_get_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *, const char*, const char*);

#endif

#ifndef SOAP_TYPE_tdt__EpcTagDataTranslation
#define SOAP_TYPE_tdt__EpcTagDataTranslation (24)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_tdt__EpcTagDataTranslation(struct soap*, struct tdt__EpcTagDataTranslation *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_tdt__EpcTagDataTranslation(struct soap*, const struct tdt__EpcTagDataTranslation *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_tdt__EpcTagDataTranslation(struct soap*, const char*, int, const struct tdt__EpcTagDataTranslation *, const char*);
SOAP_FMAC3 struct tdt__EpcTagDataTranslation * SOAP_FMAC4 soap_in_tdt__EpcTagDataTranslation(struct soap*, const char*, struct tdt__EpcTagDataTranslation *, const char*);

#ifndef soap_write_tdt__EpcTagDataTranslation
#define soap_write_tdt__EpcTagDataTranslation(soap, data) ( soap_begin_send(soap) || (soap_serialize_tdt__EpcTagDataTranslation(soap, data), 0) || soap_put_tdt__EpcTagDataTranslation(soap, data, "tdt:EpcTagDataTranslation", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_tdt__EpcTagDataTranslation(struct soap*, const struct tdt__EpcTagDataTranslation *, const char*, const char*);

#ifndef soap_read_tdt__EpcTagDataTranslation
#define soap_read_tdt__EpcTagDataTranslation(soap, data) ( soap_begin_recv(soap) || !soap_get_tdt__EpcTagDataTranslation(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct tdt__EpcTagDataTranslation * SOAP_FMAC4 soap_get_tdt__EpcTagDataTranslation(struct soap*, struct tdt__EpcTagDataTranslation *, const char*, const char*);

#ifndef SOAP_TYPE_tdt__Scheme
#define SOAP_TYPE_tdt__Scheme (22)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_tdt__Scheme(struct soap*, struct tdt__Scheme *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_tdt__Scheme(struct soap*, const struct tdt__Scheme *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_tdt__Scheme(struct soap*, const char*, int, const struct tdt__Scheme *, const char*);
SOAP_FMAC3 struct tdt__Scheme * SOAP_FMAC4 soap_in_tdt__Scheme(struct soap*, const char*, struct tdt__Scheme *, const char*);

#ifndef soap_write_tdt__Scheme
#define soap_write_tdt__Scheme(soap, data) ( soap_begin_send(soap) || (soap_serialize_tdt__Scheme(soap, data), 0) || soap_put_tdt__Scheme(soap, data, "tdt:Scheme", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_tdt__Scheme(struct soap*, const struct tdt__Scheme *, const char*, const char*);

#ifndef soap_read_tdt__Scheme
#define soap_read_tdt__Scheme(soap, data) ( soap_begin_recv(soap) || !soap_get_tdt__Scheme(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct tdt__Scheme * SOAP_FMAC4 soap_get_tdt__Scheme(struct soap*, struct tdt__Scheme *, const char*, const char*);

#ifndef SOAP_TYPE_tdt__Level
#define SOAP_TYPE_tdt__Level (19)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_tdt__Level(struct soap*, struct tdt__Level *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_tdt__Level(struct soap*, const struct tdt__Level *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_tdt__Level(struct soap*, const char*, int, const struct tdt__Level *, const char*);
SOAP_FMAC3 struct tdt__Level * SOAP_FMAC4 soap_in_tdt__Level(struct soap*, const char*, struct tdt__Level *, const char*);

#ifndef soap_write_tdt__Level
#define soap_write_tdt__Level(soap, data) ( soap_begin_send(soap) || (soap_serialize_tdt__Level(soap, data), 0) || soap_put_tdt__Level(soap, data, "tdt:Level", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_tdt__Level(struct soap*, const struct tdt__Level *, const char*, const char*);

#ifndef soap_read_tdt__Level
#define soap_read_tdt__Level(soap, data) ( soap_begin_recv(soap) || !soap_get_tdt__Level(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct tdt__Level * SOAP_FMAC4 soap_get_tdt__Level(struct soap*, struct tdt__Level *, const char*, const char*);

#ifndef SOAP_TYPE_tdt__Rule
#define SOAP_TYPE_tdt__Rule (18)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_tdt__Rule(struct soap*, struct tdt__Rule *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_tdt__Rule(struct soap*, const struct tdt__Rule *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_tdt__Rule(struct soap*, const char*, int, const struct tdt__Rule *, const char*);
SOAP_FMAC3 struct tdt__Rule * SOAP_FMAC4 soap_in_tdt__Rule(struct soap*, const char*, struct tdt__Rule *, const char*);

#ifndef soap_write_tdt__Rule
#define soap_write_tdt__Rule(soap, data) ( soap_begin_send(soap) || (soap_serialize_tdt__Rule(soap, data), 0) || soap_put_tdt__Rule(soap, data, "tdt:Rule", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_tdt__Rule(struct soap*, const struct tdt__Rule *, const char*, const char*);

#ifndef soap_read_tdt__Rule
#define soap_read_tdt__Rule(soap, data) ( soap_begin_recv(soap) || !soap_get_tdt__Rule(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct tdt__Rule * SOAP_FMAC4 soap_get_tdt__Rule(struct soap*, struct tdt__Rule *, const char*, const char*);

#ifndef SOAP_TYPE_tdt__Option
#define SOAP_TYPE_tdt__Option (16)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_tdt__Option(struct soap*, struct tdt__Option *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_tdt__Option(struct soap*, const struct tdt__Option *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_tdt__Option(struct soap*, const char*, int, const struct tdt__Option *, const char*);
SOAP_FMAC3 struct tdt__Option * SOAP_FMAC4 soap_in_tdt__Option(struct soap*, const char*, struct tdt__Option *, const char*);

#ifndef soap_write_tdt__Option
#define soap_write_tdt__Option(soap, data) ( soap_begin_send(soap) || (soap_serialize_tdt__Option(soap, data), 0) || soap_put_tdt__Option(soap, data, "tdt:Option", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_tdt__Option(struct soap*, const struct tdt__Option *, const char*, const char*);

#ifndef soap_read_tdt__Option
#define soap_read_tdt__Option(soap, data) ( soap_begin_recv(soap) || !soap_get_tdt__Option(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct tdt__Option * SOAP_FMAC4 soap_get_tdt__Option(struct soap*, struct tdt__Option *, const char*, const char*);

#ifndef SOAP_TYPE_tdt__Field
#define SOAP_TYPE_tdt__Field (13)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_tdt__Field(struct soap*, struct tdt__Field *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_tdt__Field(struct soap*, const struct tdt__Field *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_tdt__Field(struct soap*, const char*, int, const struct tdt__Field *, const char*);
SOAP_FMAC3 struct tdt__Field * SOAP_FMAC4 soap_in_tdt__Field(struct soap*, const char*, struct tdt__Field *, const char*);

#ifndef soap_write_tdt__Field
#define soap_write_tdt__Field(soap, data) ( soap_begin_send(soap) || (soap_serialize_tdt__Field(soap, data), 0) || soap_put_tdt__Field(soap, data, "tdt:Field", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_tdt__Field(struct soap*, const struct tdt__Field *, const char*, const char*);

#ifndef soap_read_tdt__Field
#define soap_read_tdt__Field(soap, data) ( soap_begin_recv(soap) || !soap_get_tdt__Field(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct tdt__Field * SOAP_FMAC4 soap_get_tdt__Field(struct soap*, struct tdt__Field *, const char*, const char*);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_PointerToSOAP_ENV__Reason (36)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Reason(struct soap*, const char *, int, struct SOAP_ENV__Reason *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason **, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Reason
#define soap_write_PointerToSOAP_ENV__Reason(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Reason(soap, data), 0) || soap_put_PointerToSOAP_ENV__Reason(soap, data, "SOAP-ENV:Reason", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Reason
#define soap_read_PointerToSOAP_ENV__Reason(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason **, const char*, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (35)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Detail(struct soap*, const char *, int, struct SOAP_ENV__Detail *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail **, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Detail
#define soap_write_PointerToSOAP_ENV__Detail(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Detail(soap, data), 0) || soap_put_PointerToSOAP_ENV__Detail(soap, data, "SOAP-ENV:Detail", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Detail
#define soap_read_PointerToSOAP_ENV__Detail(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail **, const char*, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (29)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Code(struct soap*, const char *, int, struct SOAP_ENV__Code *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code **, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Code
#define soap_write_PointerToSOAP_ENV__Code(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Code(soap, data), 0) || soap_put_PointerToSOAP_ENV__Code(soap, data, "SOAP-ENV:Code", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Code
#define soap_read_PointerToSOAP_ENV__Code(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **, const char*, const char*);

#endif

#ifndef SOAP_TYPE_PointerTotdt__Scheme
#define SOAP_TYPE_PointerTotdt__Scheme (25)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTotdt__Scheme(struct soap*, struct tdt__Scheme *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTotdt__Scheme(struct soap*, const char *, int, struct tdt__Scheme *const*, const char *);
SOAP_FMAC3 struct tdt__Scheme ** SOAP_FMAC4 soap_in_PointerTotdt__Scheme(struct soap*, const char*, struct tdt__Scheme **, const char*);

#ifndef soap_write_PointerTotdt__Scheme
#define soap_write_PointerTotdt__Scheme(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTotdt__Scheme(soap, data), 0) || soap_put_PointerTotdt__Scheme(soap, data, "tdt:Scheme", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTotdt__Scheme(struct soap*, struct tdt__Scheme *const*, const char*, const char*);

#ifndef soap_read_PointerTotdt__Scheme
#define soap_read_PointerTotdt__Scheme(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTotdt__Scheme(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct tdt__Scheme ** SOAP_FMAC4 soap_get_PointerTotdt__Scheme(struct soap*, struct tdt__Scheme **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTotdt__Level
#define SOAP_TYPE_PointerTotdt__Level (23)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTotdt__Level(struct soap*, struct tdt__Level *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTotdt__Level(struct soap*, const char *, int, struct tdt__Level *const*, const char *);
SOAP_FMAC3 struct tdt__Level ** SOAP_FMAC4 soap_in_PointerTotdt__Level(struct soap*, const char*, struct tdt__Level **, const char*);

#ifndef soap_write_PointerTotdt__Level
#define soap_write_PointerTotdt__Level(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTotdt__Level(soap, data), 0) || soap_put_PointerTotdt__Level(soap, data, "tdt:Level", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTotdt__Level(struct soap*, struct tdt__Level *const*, const char*, const char*);

#ifndef soap_read_PointerTotdt__Level
#define soap_read_PointerTotdt__Level(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTotdt__Level(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct tdt__Level ** SOAP_FMAC4 soap_get_PointerTotdt__Level(struct soap*, struct tdt__Level **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTotdt__Rule
#define SOAP_TYPE_PointerTotdt__Rule (21)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTotdt__Rule(struct soap*, struct tdt__Rule *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTotdt__Rule(struct soap*, const char *, int, struct tdt__Rule *const*, const char *);
SOAP_FMAC3 struct tdt__Rule ** SOAP_FMAC4 soap_in_PointerTotdt__Rule(struct soap*, const char*, struct tdt__Rule **, const char*);

#ifndef soap_write_PointerTotdt__Rule
#define soap_write_PointerTotdt__Rule(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTotdt__Rule(soap, data), 0) || soap_put_PointerTotdt__Rule(soap, data, "tdt:Rule", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTotdt__Rule(struct soap*, struct tdt__Rule *const*, const char*, const char*);

#ifndef soap_read_PointerTotdt__Rule
#define soap_read_PointerTotdt__Rule(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTotdt__Rule(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct tdt__Rule ** SOAP_FMAC4 soap_get_PointerTotdt__Rule(struct soap*, struct tdt__Rule **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTotdt__Option
#define SOAP_TYPE_PointerTotdt__Option (20)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTotdt__Option(struct soap*, struct tdt__Option *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTotdt__Option(struct soap*, const char *, int, struct tdt__Option *const*, const char *);
SOAP_FMAC3 struct tdt__Option ** SOAP_FMAC4 soap_in_PointerTotdt__Option(struct soap*, const char*, struct tdt__Option **, const char*);

#ifndef soap_write_PointerTotdt__Option
#define soap_write_PointerTotdt__Option(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTotdt__Option(soap, data), 0) || soap_put_PointerTotdt__Option(soap, data, "tdt:Option", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTotdt__Option(struct soap*, struct tdt__Option *const*, const char*, const char*);

#ifndef soap_read_PointerTotdt__Option
#define soap_read_PointerTotdt__Option(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTotdt__Option(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct tdt__Option ** SOAP_FMAC4 soap_get_PointerTotdt__Option(struct soap*, struct tdt__Option **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTotdt__Field
#define SOAP_TYPE_PointerTotdt__Field (17)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTotdt__Field(struct soap*, struct tdt__Field *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTotdt__Field(struct soap*, const char *, int, struct tdt__Field *const*, const char *);
SOAP_FMAC3 struct tdt__Field ** SOAP_FMAC4 soap_in_PointerTotdt__Field(struct soap*, const char*, struct tdt__Field **, const char*);

#ifndef soap_write_PointerTotdt__Field
#define soap_write_PointerTotdt__Field(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTotdt__Field(soap, data), 0) || soap_put_PointerTotdt__Field(soap, data, "tdt:Field", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTotdt__Field(struct soap*, struct tdt__Field *const*, const char*, const char*);

#ifndef soap_read_PointerTotdt__Field
#define soap_read_PointerTotdt__Field(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTotdt__Field(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct tdt__Field ** SOAP_FMAC4 soap_get_PointerTotdt__Field(struct soap*, struct tdt__Field **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTotdt__PadDirectionList
#define SOAP_TYPE_PointerTotdt__PadDirectionList (15)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTotdt__PadDirectionList(struct soap*, enum tdt__PadDirectionList *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTotdt__PadDirectionList(struct soap*, const char *, int, enum tdt__PadDirectionList *const*, const char *);
SOAP_FMAC3 enum tdt__PadDirectionList ** SOAP_FMAC4 soap_in_PointerTotdt__PadDirectionList(struct soap*, const char*, enum tdt__PadDirectionList **, const char*);

#ifndef soap_write_PointerTotdt__PadDirectionList
#define soap_write_PointerTotdt__PadDirectionList(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTotdt__PadDirectionList(soap, data), 0) || soap_put_PointerTotdt__PadDirectionList(soap, data, "tdt:PadDirectionList", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTotdt__PadDirectionList(struct soap*, enum tdt__PadDirectionList *const*, const char*, const char*);

#ifndef soap_read_PointerTotdt__PadDirectionList
#define soap_read_PointerTotdt__PadDirectionList(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTotdt__PadDirectionList(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 enum tdt__PadDirectionList ** SOAP_FMAC4 soap_get_PointerTotdt__PadDirectionList(struct soap*, enum tdt__PadDirectionList **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTotdt__CompactionMethodList
#define SOAP_TYPE_PointerTotdt__CompactionMethodList (14)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTotdt__CompactionMethodList(struct soap*, enum tdt__CompactionMethodList *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTotdt__CompactionMethodList(struct soap*, const char *, int, enum tdt__CompactionMethodList *const*, const char *);
SOAP_FMAC3 enum tdt__CompactionMethodList ** SOAP_FMAC4 soap_in_PointerTotdt__CompactionMethodList(struct soap*, const char*, enum tdt__CompactionMethodList **, const char*);

#ifndef soap_write_PointerTotdt__CompactionMethodList
#define soap_write_PointerTotdt__CompactionMethodList(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTotdt__CompactionMethodList(soap, data), 0) || soap_put_PointerTotdt__CompactionMethodList(soap, data, "tdt:CompactionMethodList", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTotdt__CompactionMethodList(struct soap*, enum tdt__CompactionMethodList *const*, const char*, const char*);

#ifndef soap_read_PointerTotdt__CompactionMethodList
#define soap_read_PointerTotdt__CompactionMethodList(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTotdt__CompactionMethodList(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 enum tdt__CompactionMethodList ** SOAP_FMAC4 soap_get_PointerTotdt__CompactionMethodList(struct soap*, enum tdt__CompactionMethodList **, const char*, const char*);

#ifndef SOAP_TYPE_xsd__integer
#define SOAP_TYPE_xsd__integer (7)
#endif

#define soap_default_xsd__integer(soap, a) soap_default_string(soap, a)


#define soap_serialize_xsd__integer(soap, a) soap_serialize_string(soap, a)

SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__integer(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_xsd__integer(struct soap*, const char*, char **, const char*);

#ifndef soap_write_xsd__integer
#define soap_write_xsd__integer(soap, data) ( soap_begin_send(soap) || (soap_serialize_xsd__integer(soap, data), 0) || soap_put_xsd__integer(soap, data, "byte", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__integer(struct soap*, char *const*, const char*, const char*);

#ifndef soap_read_xsd__integer
#define soap_read_xsd__integer(soap, data) ( soap_begin_recv(soap) || !soap_get_xsd__integer(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_xsd__integer(struct soap*, char **, const char*, const char*);

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
#endif

#define soap_default__QName(soap, a) soap_default_string(soap, a)


#define soap_serialize__QName(soap, a) soap_serialize_string(soap, a)

SOAP_FMAC3 int SOAP_FMAC4 soap_out__QName(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__QName(struct soap*, const char*, char **, const char*);

#ifndef soap_write__QName
#define soap_write__QName(soap, data) ( soap_begin_send(soap) || (soap_serialize__QName(soap, data), 0) || soap_put__QName(soap, data, "byte", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put__QName(struct soap*, char *const*, const char*, const char*);

#ifndef soap_read__QName
#define soap_read__QName(soap, data) ( soap_begin_recv(soap) || !soap_get__QName(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__QName(struct soap*, char **, const char*, const char*);

#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (4)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_string(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_string(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_string(struct soap*, const char*, char **, const char*);

#ifndef soap_write_string
#define soap_write_string(soap, data) ( soap_begin_send(soap) || (soap_serialize_string(soap, data), 0) || soap_put_string(soap, data, "byte", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_string(struct soap*, char *const*, const char*, const char*);

#ifndef soap_read_string
#define soap_read_string(soap, data) ( soap_begin_recv(soap) || !soap_get_string(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_string(struct soap*, char **, const char*, const char*);

#ifdef __cplusplus
}
#endif

#endif

/* End of soapH.h */
